### ISSUE TITLE
Seance Contenu (Prof - Etudiant)

### ISSUE THREAD

**Issue by Elaissaoui-Ali-Sim** [sim-fpt-usmba/E_learning#9]
we should add the "contenu" to the seance activity.
so we need to add all the componenets to the fragment "contenu":
- the time date of the seance
- a text area for the seance's descriptives
- an area to put files in to be downloaded
- an area to put audios in to be downloaded

![photo_2020-04-22_02-08-55](https://user-images.githubusercontent.com/62296488/79933040-637a0000-843e-11ea-9702-866b10d4a1af.jpg)

![photo_2020-04-22_02-08-55 (2)](https://user-images.githubusercontent.com/62296488/79933042-64129680-843e-11ea-8672-2b782ff750ec.jpg)

**Comment by Tareq-Hr** [comment]
It's my Task

**Comment by Tareq-Hr** [comment]
Done
